name: 'Pytest run'
description: 'Greet someone'
inputs:
  python-version:  # id of input
    description: 'Python version to use'
    required: true
  elasticsearch:
    description: 'Elasticsearch version'
    required: true
runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v3
    with:
      python-version: ${{ inputs.python-version }}
  - uses: actions/cache@v3
    with:
      path: ~/elasticsearch
      key: elasticsearch-${{ inputs.elasticsearch }}
  - name: Setup elasticsearch
    uses: ankane/setup-elasticsearch@v1
    with:
      elasticsearch-version: ${{ inputs.elasticsearch }}
  - name: Stop running elasticsearch
    shell: bash
    run: killall elasticsearch
  - name: Run test
    uses: fizyk/actions-reuse/.github/actions/pipenv@v2.1.2
    with:
      python-version: ${{ matrix.python-version }}
      pipenv-install-options: "--skip-lock"
      command: pytest --elasticsearch-executable=$ES_HOME/bin/elasticsearch -n 0 --cov-report=xml
  - name: Run xdist test
    uses: fizyk/actions-reuse/.github/actions/pipenv@v2.1.2
    with:
      python-version: ${{ matrix.python-version }}
      pipenv-install-options: "--skip-lock"
      command: pytest --elasticsearch-executable=$ES_HOME/bin/elasticsearch -n 1 --cov-report=xml:coverage-xdist.xml
  - name: Upload coverage to Codecov
    uses: codecov/codecov-action@v3.0.0
    with:
      flags: linux,elastic-${{ inputs.elasticsearch }}
      env_vars: OS, PYTHON
      fail_ci_if_error: false